language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: mvn -f /home/travis/build/Arthyom/MigracionCaadi/CaadiMigrate/pom.xml test -B  install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
