use CaadiIntegrada;

insert into tipo_libro(tipo_libro) values('Theory');
insert into tipo_libro(tipo_libro) values('Workbook');
insert into tipo_libro(tipo_libro) values('Answer');

insert into nivel(nivel) values('Basic');
insert into nivel(nivel) values('Benninger');
insert into nivel(nivel) values('Pre-Intermediate');
insert into nivel(nivel) values('Intermediate');
insert into nivel(nivel) values('Pre-Advanced');
insert into nivel(nivel) values('Advanced');
insert into nivel(nivel) values('None');

insert into rating(rating) values(0);
insert into rating(rating) values(1);
insert into rating(rating) values(2);
insert into rating(rating) values(3);
insert into rating(rating) values(4);
insert into rating(rating) values(5);

insert into idioma(idioma) values('English');
insert into idioma(idioma) values('French');
insert into idioma(idioma) values('Italian');
insert into idioma(idioma) values('German');

insert into area_libro(area_libro) values('Grammar');
insert into area_libro(area_libro) values('Listening');
insert into area_libro(area_libro) values('Reading');
insert into area_libro(area_libro) values('Speaking');
insert into area_libro(area_libro) values('Vocabulary');

insert into editorial(nombre_editorial) values('None');
insert into editorial(nombre_editorial) values('Cambridge');
insert into editorial(nombre_editorial) values('Thomson Heinle');
insert into editorial(nombre_editorial) values('Oxford');
insert into editorial(nombre_editorial) values('Collins COBUILD');
insert into editorial(nombre_editorial) values('Houghton Mifflin');
insert into editorial(nombre_editorial) values('mmpublications');
insert into editorial(nombre_editorial) values('Express Publishing');
insert into editorial(nombre_editorial) values('FootPrint Reading Library');
insert into editorial(nombre_editorial) values('Pearson Longman');
insert into editorial(nombre_editorial) values('Heinle Cengage Learning');
insert into editorial(nombre_editorial) values('National Geographic');
insert into editorial(nombre_editorial) values('Editorial ');
insert into editorial(nombre_editorial) values('Richmond Publishing');
insert into editorial(nombre_editorial) values('The University of Michigan Press');
insert into editorial(nombre_editorial) values('The Wright Group');
insert into editorial(nombre_editorial) values('Scholastic Inc.');
insert into editorial(nombre_editorial) values('Anglia Television Limeted');
insert into editorial(nombre_editorial) values('Walker and Company');
insert into editorial(nombre_editorial) values('Stanford University Press');
insert into editorial(nombre_editorial) values('Heinle & Heinle Publishers');
insert into editorial(nombre_editorial) values('Scholastic Book Servies');
insert into editorial(nombre_editorial) values('A yerling Book Dell Publishing');
insert into editorial(nombre_editorial) values('The New American Library');
insert into editorial(nombre_editorial) values('A batam book');
insert into editorial(nombre_editorial) values('Pocket');
insert into editorial(nombre_editorial) values('The group');
insert into editorial(nombre_editorial) values('BestSeller');
insert into editorial(nombre_editorial) values('Faucett');
insert into editorial(nombre_editorial) values('Penguin classic');
insert into editorial(nombre_editorial) values('A corgi book');
insert into editorial(nombre_editorial) values('National BestSeller');
insert into editorial(nombre_editorial) values('Harper & Row Publishers');
insert into editorial(nombre_editorial) values('Earts Children');
insert into editorial(nombre_editorial) values('Thomson');
insert into editorial(nombre_editorial) values('LTP Business');
insert into editorial(nombre_editorial) values('LTP Language');
insert into editorial(nombre_editorial) values('COBUILD');
insert into editorial(nombre_editorial) values('Heinles Newbury House');
insert into editorial(nombre_editorial) values('LIMUSA');
insert into editorial(nombre_editorial) values('Longman');

insert into autor(nombre_autorlibro,apellido_autorlibro)  values('None','None');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Raymond','Murphy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Thomson','Heinle');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Michael','Duckworth');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Michael','McCarthy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Dave',' Willis');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('John','Murphy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('David','Hardsity');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Martha','Graves');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Patricia A.','Dunkel');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('David','Nunan');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Peggy','Marcy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Charles','Perrault');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('L. Frank','Baum');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('H.Q.','Mitchell');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jules','Verne');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Alexandre ','Dumas');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Daniel','Defoe');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('J. Meade ','Falkner');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Rudyard','Kipling');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Johanna','Spyri');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jane','Rollason');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Bernard','Smith');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Dewwy','Gram');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('William','Shakespeare');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Winston','Groom');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mary','McIntosh');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Oscar','Wilde');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Tim','Vicary');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Rosemary','Border');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('John','Grisham');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('James','Fenimore Cooper');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jenny','Dooley');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Virgina','Evans');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jonathan','Swift');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mark','Twain');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('National Geographic','');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Raymond','Chandler');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('O. Henry','');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Robert','Russell');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jack','London ');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Charlotte','Bronte');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('J. M.','Dillar');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Patricia','Hermes');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Vicky','Shipton');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Anna','Sewell');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Lewis','Carroll');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Charles','Dickens');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Gaston','Leroux');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mary','Shelley');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('J.M.','Dillard');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Simon','Greenall');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Keith S.','Folse');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jann','Hulzenga');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Peter',' Viney');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Kevin','King');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Sarah','Cunningham');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Bill','Bowler');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('W.S.','Flowler');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('James','Wallis');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Richard','Gunther');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Ron','Roy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('David','Rowe');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Barthe','DeClements');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Terri','Fields');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Francis','Kalnay');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('William H.',' Durham');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jean A.',' McConochie');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Keith','Allan');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Robert','Kimmel Smith');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Bill','Sands');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Tom','Robbins');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Vera','Csopary');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mary','McCarthy');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('David','Wallechinsky');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Darwin T.','Turner');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Henry','James ');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('James','Baldwin ');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jhon','Mcphee');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Pete','Townshend');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Charles L.','Hamrum');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Carlos','Fuentes');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Lorraine C.',' Smith');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Louisa','May');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Edgar Alan',' Poe');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Robert Louis','Stevenson');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jean M.','Auel');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jenny','Doley');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Robert Louis','');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Santiago','Remacha Esteras');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Guillian D.',' Brown');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Ian','Mackenzie');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Dinos','Demetriades');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Lindsay','White');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Barbara','Garside');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('B. Jean','Naterop');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Malcolm','Goodale');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Bill','Mascull');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('John',' Flower');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Collins','');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Kathryn','Trump');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Garcia','Diaz');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Marilyn S.','Rosenthal');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Norma',' Shapiro');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jonathan','Marks');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mark','Hancock');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Martin','Hewings');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('William R.','Smalzer');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Felicity',"O'Dell");
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Phyllis L.','Lim');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Leslie','Bohem');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Brigit','Viney');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Roberto','Rodat');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Vice','Mckevin');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Diana','Pye');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Linga','Hulzenga');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Karen','Viney');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Peter','Moor');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Sue','Parminter');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Bill','Browler');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Kate','Burridge');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Elena Marco','Fabre');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Sally','Rice');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Tony','Garside');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Rod','Revell');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Michael','Berman');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Mark','Powell');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Ron','Martinez');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Sherry','Trechter');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Dee Ann Holisky','Holisky');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Daniel B.',' Freeman');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jayme','Adelson-Goldstein');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Jon','Wright');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Nelson','');
insert into autor(nombre_autorlibro,apellido_autorlibro)  values('Elizabeth',' Gray');

insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(1 , 9780521625982 , 1,1,'2002', "Grammar in use Intermediate, Self-study referenceand practice for students of English",1,TRUE,1,2,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(2 , 9780521797184 , 1,1,'2003', "Basic Grammar in use, Workbook with answer",2,TRUE,1,2,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(3 , 9780521626002 , 1,1,'2003', "Basic Grammar in use, Self-study referenceand practice for students of English",1,TRUE,1,2,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(4 , 9780521797207 , 1,1,'2002', "Grammar in use Intermediate, Workbook with answer",2,TRUE,1,2,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(5 , 9780838418932 , 1,1,'2001', "More Grammar Practice 1",2,TRUE,1,3,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(6 , 9780838419021 , 1,1,'2001', "More Grammar Practice 2",2,TRUE,1,3,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(7 , 9780838419472 , 1,1,'2001', "More Grammar Practice 3",2,TRUE,1,3,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(8 , 9780838419489 , 1,1,'2001', "More Grammar Answer Key",3,TRUE,1,3,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(9 , 9780194576253 , 1,1,'', "Essential Business Grammar & Practice, Elementary to Pre-Intermediate",1,TRUE,1,4,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(10 , 9780194570794 , 1,1,'', "Business Grammar & Practice, New Edition",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(11 , 9780521603782 , 1,1,'', "English Collocations in Use",1,TRUE,1,2,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(12 , 9780521789578 , 1,1,'', "English Idioms in Use",1,TRUE,1,2,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(13 , 9780007143092 , 1,1,'2003', "Elementary English Grammar ",1,TRUE,1,5,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(14 , 9781424004485 , 1,1,'', "Grammar Clips Workbook",2,TRUE,1,3,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(15 , 9780194591881 , 1,2,'', "New Headway Video Elementary Student's Book ",2,TRUE,1,4,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(16 , 9780194591898 , 1,2,'', "New Headway Video Elementary Teacher's Book ",1,TRUE,1,4,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(17 , 9780194581790 , 1,2,'', "New Headway Video Beginner Teacher's Book ",1,TRUE,1,4,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(18 , 9780194581783 , 1,2,'', "New Headway Video Beginner Student's Book ",2,TRUE,1,4,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(19 , 9780194581806 , 1,2,'', "New Headway Video Pre-Intermediate Student's Book ",2,TRUE,1,4,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(20 , 9780194581813 , 1,2,'', "New Headway Video Pre-Intermediate Teacher's Book ",1,TRUE,1,4,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(21 , 9780194581882 , 1,2,'', "New Headway Video Intermediate Student's Book ",2,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(22 , 9780194581899 , 1,2,'', "New Headway Video Intermediate Teacher's Book ",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(23 , 9780838430125 , 1,2,'', "Listen Speak Present A step by step Presenter's Workbook ",2,TRUE,1,1,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(24 , 9781413012576 , 1,2,'', "Listening and Notetaking Skills ",1,TRUE,1,1,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(25 , 9780838404188 , 1,2,'', "Listen In ",1,TRUE,1,3,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(26 , 9780618353057 , 1,2,'', "Step up Listening, Speaking and Critical Thinking",1,TRUE,1,6,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(27 , 9780618353064 , 1,2,'', "Step up Listening, Speaking and Critical Thinking",1,TRUE,1,6,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(28 , 9780604430758 , 1,2,'', "BEAUTY AND THE BEAST",1,TRUE,1,7,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(29 , 9789603797159 , 1,2,'', "The Table The Ass And The Stick",1,TRUE,1,7,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(30 , 9789603797180 , 1,2,'', "The Wizard Of OZ",1,TRUE,1,7,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(31 , 9789603796930 , 1,2,'', "Robin Hood",1,TRUE,1,7,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(32 , 9789603796770 , 1,2,'', "The Wishing Fish",1,TRUE,1,7,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(33 , 9789603790723 , 1,2,'', "Captain Grant’s Children",1,TRUE,1,7,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(34 , 9781843256687 , 1,2,'', "The Man In The Iron Mask",1,TRUE,1,8,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(35 , 9781842167977 , 1,2,'', "Robinson Crusoe",1,TRUE,1,8,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(36 , 9789603794660 , 1,2,'', "Aladdin",1,TRUE,1,7,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(37 , 9781424011568 , 1,2,'', "Snow Magic!",1,TRUE,1,9,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(38 , 9781424011438 , 1,2,'', "Party",1,TRUE,1,9,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(39 , 9781424011445 , 1,2,'', "Happy Elephants",1,TRUE,1,9,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(40 , 9781424011544 , 1,2,'', "The Causeway",1,TRUE,1,9,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(41 , 9781405842884 , 1,2,'', "Moonfleet",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(42 , 9781405842860 , 1,2,'', "The Jungle Book",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(43 , 9781405842853 , 1,2,'', "Heidi",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(44 , NULL , 1,2,'', "Gandhi",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(45 , 9781405881494 , 1,2,'', "David Beckham",1,TRUE,1,10,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(46 , 9781405869737 , 1,2,'', "Dante’s Peak",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(47 , 9781424028702 , 1,2,'', "Macbeth",1,TRUE,1,11,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(48 , 9781424011650 , 1,2,'', "The Last Of The Cheju Divers",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(49 , 9781424011582 , 1,2,'', "Farley The Red Panda",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(50 , 9781424011629 , 1,2,'', "The Knife Markets Of Sanaa",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(51 , 9781424011476 , 1,2,'', "Life on the Orinoco",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(52 , 9781405876759 , 1,2,'', "Forrest Gump",1,TRUE,1,10,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(53 , 9780194233958 , 1,2,'', "Disaster!",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(54 , 9780194791267 , 1,2,'', "The Picture Of Dorian Gray",1,TRUE,1,4,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(55 , 9780194789042 , 1,2,'', "The Elephant Man",1,TRUE,1,4,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(56 , 9780194234207 , 1,2,'', "Drive Into Danger",1,TRUE,1,4,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(57 , 9781424011704 , 1,2,'', "The Memory Man",1,TRUE,1,12,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(58 , 9781424011612 , 1,2,'', "A Special Kind Of Neighborhood",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(59 , 9781405882552 , 1,2,'', "A Time to Kill",1,TRUE,1,10,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(60 , 9789604430796 , 1,2,'', "Excalibur",1,TRUE,1,7,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(61 , 9781842167915 , 1,2,'', "The Last Of The Mohicans",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(62 , 9781843251552 , 1,2,'', "20,000 Leagues Under The Sea",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(63 , 9781842164761 , 1,2,'', "Life Exchange",1,TRUE,1,13,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(64 , 9789603611516 , 1,2,'', "Orphevs DescenDing",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(65 , 9781842164747 , 1,2,'', "Perseus and Andromeda",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(66 , 9781842164754 , 1,2,'', "Simon Decker & The Secret Formula",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(67 , 9781842169032 , 1,2,'', "Swan Lake",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(68 , 9789603790884 , 1,2,'', "Save the Forest",1,TRUE,1,7,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(69 , 9789603790846 , 1,2,'', "Lisa Visits Loch Ness",1,TRUE,1,7,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(70 , 9789603790921 , 1,2,'', "Lost in the Cave",1,TRUE,1,7,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(71 , 9781845581756 , 1,2,'', "David Coperfield",1,TRUE,1,8,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(72 , 9789603796893 , 1,2,'', "Gulliver in Lilliput",1,TRUE,1,7,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(73 , 9789603796817 , 1,2,'', "Theseus and the minotaur",1,TRUE,1,7,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(74 , 9789603796855 , 1,2,'', "Tom Sawyer",1,TRUE,1,7,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(75 , 9781424011483 , 1,2,'', "The young readers of Mongolia",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(76 , 9781424011537 , 1,2,'', "Volcano trek ",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(77 , 9781424011421 , 1,2,'', "Artic whale danger",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(78 , 9781405869751 , 1,2,'', "The lady in the lake",1,TRUE,1,10,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(79 , 9781405842785 , 1,2,'', "The gift of the magi and other stories",1,TRUE,1,10,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(80 , 9781884661497 , 1,2,'', "Oliver twist",1,TRUE,1,8,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(81 , 9781844668427 , 1,2,'', "White fang",1,TRUE,1,8,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(82 , 9788446818698 , 1,2,'', "Batman begins",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(83 , 9781844662371 , 1,2,'', "Jane Eyre",1,TRUE,1,8,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(84 , 9781424011575 , 1,2,'', "Gorilla Watching tour",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(85 , 9781424011698 , 1,2,'', "Dinosaur Search",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(86 , 9781405862394 , 1,2,'', "Jim Smiley and his jumping. Frog and other histories",1,TRUE,1,10,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(87 , 9781405876919 , 1,2,'', "The fugitive",1,TRUE,1,10,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(88 , 9781424011537 , 1,2,'', "The Story of The Hula",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(89 , 9789603790808 , 1,2,'', "Paul and Pierre in Paris",1,TRUE,1,7,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(90 , 9781845586096 , 1,2,'', "Journey to the centre of the Earth",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(91 , 9781844662142 , 1,2,'', "Oliver twist",1,TRUE,1,8,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(92 , 9789603794356 , 1,2,'', "Mowgli",1,TRUE,1,7,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(93 , 9789604430369 , 1,2,'', "Jingle`s Chistmas Adcenture",1,TRUE,1,7,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(94 , 9789603794349 , 1,2,'', "The Fox & The Dog",1,TRUE,1,7,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(95 , 9789603794363 , 1,2,'', "Cookie Land",1,TRUE,1,7,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(96 , 9781424011681 , 1,2,'', "Wild Animal Trackers",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(97 , 9781424011469 , 1,2,'', "The Lost City of Machu Picchu",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(98 , 9781424011452 , 1,2,'', "The Future of a Village",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(99 , 9781424011513 , 1,2,'', "Don't Believe Your Eyes!",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(100 , 9781424011506 , 1,2,'', "Columbus and the New World",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(101 , 9781424011490 , 1,2,'', "Dreamtime Painters",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(102 , 9781421011520 , 1,2,'', "Alaskan ICE Climbing",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(103 , 9781405869515 , 1,2,'', "Ffy Away Home",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(104 , 9781405867658 , 1,2,'', "Daniel Redcliffe",1,TRUE,1,10,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(105 , 9781405855358 , 1,2,'', "American Life",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(106 , 9781405842815 , 1,2,'', "Black Beauty",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(107 , 9781405855358 , 1,2,'', "Alice in Wonderland",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(108 , 9781844663750 , 1,2,'', "David Copperfield",1,TRUE,1,8,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(109 , 9781844669585 , 1,2,'', "The Phantom of the Opera",1,TRUE,1,8,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(110 , 9781424028757 , 1,2,'', "Henry V",1,TRUE,1,11,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(111 , 9781424031818 , 1,2,'', "Frankenstein",1,TRUE,1,11,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(112 , 9781424028795 , 1,2,'', "Great Expectations",1,TRUE,1,11,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(113 , 9781424011605 , 1,2,'', "A Disappearing World",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(114 , 9781424011667 , 1,2,'', "Cheese-Rolling Races",1,TRUE,1,9,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(115 , 9781405862431 , 1,2,'', "Macbeth",1,TRUE,1,10,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(116 , 9781405865289 , 1,2,'', "Great Expectations",1,TRUE,1,10,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(117 , 9789602797180 , 1,2,'', "The Magic Ring",1,TRUE,1,10,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(118 , 9781405876919 , 1,2,'', "The fugitive",1,TRUE,1,10,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(119 , NULL , 1,3,'', "Reading 3",1,TRUE,1,2,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(120 , 9780472083847 , 1,3,'', "Beginning Reading Practices, Building Reading and Vocabulary Strategies",1,TRUE,1,15,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(121 , 9780194302036 , 1,3,'', "Book 1, Totally True, Building Vocabulary Through Reading ",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(122 , 9780194302043 , 1,3,'', "Book 2, Totally True, Building Vocabulary Through Reading ",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(123 , 9780194302050 , 1,3,'', "Book 3, Totally True, Building Vocabulary Through Reading ",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(124 , 9780194590297 , 1,3,'', "Wallece & Gromit in The Wrong Trousers, Student's Book",1,TRUE,1,4,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(125 , 9780194590303 , 1,3,'', "Wallece & Gromit in The Wrong Trousers, Teacher's Book",1,TRUE,1,4,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(126 , 9780395917121 , 1,3,'', "The Big Picture, Idioms as Metaphors",1,TRUE,1,6,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(127 , 9780194592437 , 1,3,'', "Wallece & Gromit in A Close Shave, Student's Book",1,TRUE,1,4,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(128 , 9789685699112 , 1,3,'', "Technlogy & The Future,Theacher's Guide, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(129 , 9789685699068 , 1,3,'', "Technlogy & The Future, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(130 , 9789685699037 , 1,3,'', "Nature & Environment, Plus Activities, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(131 , 9789685699129 , 1,3,'', "Technlogy & The Future,Theacher's Guide, Level 2",1,TRUE,1,14,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(132 , 9789685699099 , 1,3,'', "Nature & Environment, Teacher's Guide, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(133 , 9789685699044 , 1,3,'', "Nature & Environment, Plus Activities, Level 2",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(134 , 9789685699105 , 1,3,'', "Nature & Environment, Teacher's Guide, Level 2",1,TRUE,1,14,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(135 , 9789685699013 , 1,3,'', "Business & Management, Plus Activities, Leve 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(136 , 9789685699051 , 1,3,'', "Technlogy & The Future,Theacher's Guide, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(137 , 9789685699075 , 1,3,'', "Business & Management, Theacher's Guide, Level 1",1,TRUE,1,14,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(138 , 9789685699020 , 1,3,'', "Business & Management, Plus Activities, Level 2",1,TRUE,1,14,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(139 , 9789685699082 , 1,3,'', "Business & Management, Theacher's Guide, Level 2",1,TRUE,1,14,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(140 , 9780194346211 , 1,3,'', "New Headway pronunciation, Elementary Student's Practice Book",1,TRUE,1,4,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(141 , 9780194376235 , 1,3,'', "New Headway pronunciation,Pre-Intermediate Student's Practice Book",1,TRUE,1,4,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(142 , 9780194362450 , 1,3,'', "New Headway pronunciation, Intermediate Student's Practice Book",1,TRUE,1,4,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(143 , 9780194362474 , 1,3,'', "New Headway pronunciation, Upper-Intermediate Student's Practice Book",1,TRUE,1,4,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(144 , 9780175559923 , 1,3,'', "Sysnthesis Advanced",1,TRUE,1,1,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(145 , 9780140376302 , 1,3,'', "Sonic the Hedgehog, Adventure 2 Gambook, Zone rangers",1,TRUE,1,1,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(146 , 799070418432-2 , 1,3,'', "Out of the Sunless Land",1,TRUE,1,16,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(147 , 9780439444637 , 1,3,'', "A to Z Mysteries The School Skeleton",1,TRUE,1,17,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(148 , 9780440863175 , 1,3,'', "Knightmare, The Forbidden Gate",1,TRUE,1,18,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(149 , NULL , 1,3,'', "The Fourth Grade Wizards",1,TRUE,1,17,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(150 , 07807300275-7 , 1,3,'', "Fourth-Graders Don't Believe in Witches",1,TRUE,1,17,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(151 , 9780802773876 , 1,3,'', "Chucaro: Wild Pony of th Pampa",1,TRUE,1,19,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(152 , NULL , 1,3,'', "Scarcity and Survival in Central America, Ecological Orgins of the Soccer War",1,TRUE,1,20,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(153 , 9780838448502 , 1,3,'', "20Th Century American Short Storis",1,TRUE,1,21,1,6);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(154 , 9780521525640 , 1,3,'', "Forbidden Words, Taboo and the Censoring of Language",1,TRUE,1,2,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(155 , NULL , 1,3,'', "Robinson Crusoe",1,TRUE,1,22,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(156 , NULL , 1,3,'', "Arthur Conan Doyle, The Exploits of Brigadier Gerand",1,TRUE,1,1,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(157 , NULL , 1,3,'', "Chocolate Fever",1,TRUE,1,23,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(158 , NULL , 1,3,'', "My Shadow Ran Fast",1,TRUE,1,24,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(159 , 778300395 , 1,3,'', "Even cowgirls get the blues",1,TRUE,1,25,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(160 , NULL , 1,3,'', "The secret of Elizabeth",1,TRUE,1,26,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(161 , NULL , 1,3,'', "A charmed life ",1,TRUE,1,27,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(162 , 778300395 , 1,3,'', "The book of list",1,TRUE,1,28,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(163 , NULL , 1,3,'', "Black Drama In America",1,TRUE,1,29,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(164 , 97801404382 , 1,3,'', "The aspern papers and the turn off the screw ",1,TRUE,1,30,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(165 , NULL , 1,3,'', "Another country",1,TRUE,1,31,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(166 , NULL , 1,3,'', "Goming into the country",1,TRUE,1,32,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(167 , NULL , 1,3,'', "MAN",1,TRUE,1,1,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(168 , NULL , 1,3,'', "Horse's Neck",1,TRUE,1,33,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(169 , NULL , 1,3,'', "Darwin's Legacy",1,TRUE,1,33,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(170 , NULL , 1,3,'', "The old gringo",1,TRUE,1,32,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(171 , 9781413000757 , 1,3,'', "Themes for today",1,TRUE,1,3,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(172 , 9781413000764 , 1,3,'', "Insights for today",1,TRUE,1,3,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(173 , 9780759398269 , 1,3,'', "Reading for today",1,TRUE,1,3,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(174 , 9781413000771 , 1,3,'', "Issues for today",1,TRUE,1,3,1,3);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(175 , 9781413000778 , 1,3,'', "Concept for today",1,TRUE,1,3,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(176 , 9781413000795 , 1,3,'', "Topic for today",1,TRUE,1,3,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(177 , 9780759398160 , 1,3,'', "Reading for today",1,TRUE,1,3,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(178 , 9780759398788 , 1,3,'', "Little woman",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(179 , 9780759398818 , 1,3,'', "David Copperfield",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(180 , 9781424005543 , 1,3,'', "Tales of mistery and terror",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(181 , 9780759398801 , 1,3,'', "The strange case Dr. Jekill and Mr. Hyde",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(182 , 9780517580493 , 1,3,'', "The plains of passage",1,TRUE,1,34,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(183 , NULL , 1,3,'', "To be Revolutionary",1,TRUE,1,33,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(184 , 9781842169056 , 1,3,'', "Hampton House",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(185 , 9789605610717 , 1,3,'', "The golden stone saga 2",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(186 , 9781843256809 , 1,3,'', "The golden stone saga 1",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(187 , 9781842163771 , 1,3,'', "Frankeistein",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(188 , 9781842167878 , 1,3,'', "Dr. Jekyll & Mr. Hyde",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(189 , 9781843255499 , 1,3,'', "Jeath squad",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(190 , 9781842166192 , 1,3,'', "Counc Vlad",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(191 , 9781843256458 , 1,3,'', "Chrismas carol",1,TRUE,1,8,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(192 , 9781842164778 , 1,3,'', "The blue scarab",1,TRUE,1,8,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(193 , 9781842169001 , 1,3,'', "Blackbeard's treasure",1,TRUE,1,8,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(194 , NULL , 1,5,'', "",1,TRUE,1,1,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(195 , 9781413030099 , 1,5,'', "English for Professional Success",1,TRUE,1,35,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(196 , 9781424000074 , 1,5,'', "English for Professional Success Teacher's Resource Book",1,TRUE,1,35,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(197 , 9780521685429 , 1,5,'', "Professional English in Use For Computers and the Internet ICT",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(198 , 9780521685429 , 1,5,'', "Professional English in Use Law",1,TRUE,1,2,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(199 , 9780521616270 , 1,5,'', "Professional English in Use Finance",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(200 , NULL , 1,5,'', "Information Technology",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(201 , NULL , 1,5,'', "Engineering",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(202 , 9780521783880 , 1,5,'', "Essential Telephoning in English Student's Book",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(203 , 9780521783897 , 1,5,'', "Essential Telephoning in English Teacher's Book",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(204 , 9780521539111 , 1,5,'', "Telephoning in English",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(205 , 9780906717462 , 1,5,'', "The Language of Meetings",1,TRUE,1,36,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(206 , 9780521532884 , 1,5,'', "Infotech English for Computer Users",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(207 , 9780521754286 , 1,5,'', "Infotech English for Computer Users Student's Book",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(208 , NULL , 1,5,'', "Infotech English for Computer Users Teacher's Book",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(209 , 9780521788656 , 1,5,'', "Basic Vocabulary in use Self-Study Reference and Practice for Students of English",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(210 , 9780521606219 , 1,5,'', "Business Vocanulary in Use Elementary",1,TRUE,1,2,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(211 , 9780521775298 , 1,5,'', "Business Vocanulary in Use Intermediate",1,TRUE,1,2,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(212 , 9780521540704 , 1,5,'', "Business Vocabulary in Use Advanced",1,TRUE,1,2,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(213 , 9780906717677 , 1,5,'', "American Vocabulary Program 1 Lower Intermediate",1,TRUE,1,37,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(214 , 9780906717707 , 1,5,'', "American Vocabulary Program 2 Intermediate",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(215 , 9780906717714 , 1,5,'', "American Vocabulary Program 3 Upper Intermediate",1,TRUE,1,37,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(216 , 9780007131785 , 1,5,'', "Phrasal Verbs Workbook",1,TRUE,1,38,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(217 , 9780007134007 , 1,5,'', "Idioms Workbook",1,TRUE,1,38,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(218 , 9780007190232 , 1,5,'', "Business Vocabulary in Practice",1,TRUE,1,38,1,5);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(219 , 9780838422809 , 1,5,'', "Walk, Amble, Stroll Vocabulary Building Through Domains Level 2",1,TRUE,1,21,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(220 , 9780838439562 , 1,5,'', "Walk, Amble, Stroll Vocabulary Building Through Domains Level 1",1,TRUE,1,21,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(221 , 9780838459850 , 1,5,'', "Instructor's Manual Walk, Amble, Stroll Level 1 and Level 2",1,TRUE,1,3,1,1);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(222 , 9780194316965 , 1,5,'', "Really Learn 100 Phrasal Verbs for Business",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(223 , 9780883770177 , 1,5,'', "Dictionary of American English",1,TRUE,1,39,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(224 , NULL , 1,5,'', "Student's Dictionary Plus Grammar",1,TRUE,1,38,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(225 , 9780194316170 , 1,5,'', "Business English Dictionary for Learners of English",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(226 , 9780194311298 , 1,5,'', "Guide to British and American Culture",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(227 , 9780194316491 , 1,5,'', "Advanced Learner's Dictionary",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(228 , 9789681853976 , 1,5,'', "Diccionario Tecnico Technical Dictionary",1,TRUE,1,40,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(229 , 9780582511576 , 1,5,'', "Diccionario Pocket",1,TRUE,1,10,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(230 , 9780801300042 , 1,5,'', "Photo Dictionary",1,TRUE,1,41,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(231 , 9781413004441 , 1,5,'', "The Heinle Picture Dictionary",1,TRUE,1,3,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(232 , NULL , 1,5,'', "Picture Dictionary",1,TRUE,1,4,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(233 , 9780521577687 , 1,5,'', "Vocabulary in Use Upper Intermediate Self-Study Reference and Practice for Students of English",1,TRUE,1,2,1,7);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(234 , 9780521693738 , 1,4,'', "English Pronuntiation in Use",1,TRUE,1,2,1,2);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(235 , 9780521687522 , 1,4,'', "English Pronuntiation in Use",1,TRUE,1,2,1,4);
insert into libro(id_libro,cod_bar,cantidad,id_area_libro,año_publicacion,titulo_libro,id_tipo_libro,audio_libro,id_rating,id_editorial,id_idioma,id_nivel) values(236 , 9780521693769 , 1,4,'', "English Pronuntiation in Use",1,TRUE,1,2,1,6);

insert into autor_libro(id_libro,id_autor) values(1,2);
insert into autor_libro(id_libro,id_autor) values(1,108);
insert into autor_libro(id_libro,id_autor) values(2,2);
insert into autor_libro(id_libro,id_autor) values(2,108);
insert into autor_libro(id_libro,id_autor) values(3,2);
insert into autor_libro(id_libro,id_autor) values(3,108);
insert into autor_libro(id_libro,id_autor) values(4,2);
insert into autor_libro(id_libro,id_autor) values(4,108);
insert into autor_libro(id_libro,id_autor) values(5,3);
insert into autor_libro(id_libro,id_autor) values(6,3);
insert into autor_libro(id_libro,id_autor) values(7,3);
insert into autor_libro(id_libro,id_autor) values(8,3);
insert into autor_libro(id_libro,id_autor) values(9,4);
insert into autor_libro(id_libro,id_autor) values(10,4);
insert into autor_libro(id_libro,id_autor) values(11,5);
insert into autor_libro(id_libro,id_autor) values(11,109);
insert into autor_libro(id_libro,id_autor) values(12,5);
insert into autor_libro(id_libro,id_autor) values(12,109);
insert into autor_libro(id_libro,id_autor) values(13,6);
insert into autor_libro(id_libro,id_autor) values(13,133);
insert into autor_libro(id_libro,id_autor) values(14,3);
insert into autor_libro(id_libro,id_autor) values(15,7);
insert into autor_libro(id_libro,id_autor) values(16,7);
insert into autor_libro(id_libro,id_autor) values(17,7);
insert into autor_libro(id_libro,id_autor) values(18,7);
insert into autor_libro(id_libro,id_autor) values(19,7);
insert into autor_libro(id_libro,id_autor) values(20,7);
insert into autor_libro(id_libro,id_autor) values(21,8);
insert into autor_libro(id_libro,id_autor) values(21,41);
insert into autor_libro(id_libro,id_autor) values(22,8);
insert into autor_libro(id_libro,id_autor) values(22,41);
insert into autor_libro(id_libro,id_autor) values(23,9);
insert into autor_libro(id_libro,id_autor) values(24,10);
insert into autor_libro(id_libro,id_autor) values(24,110);
insert into autor_libro(id_libro,id_autor) values(25,11);
insert into autor_libro(id_libro,id_autor) values(26,12);
insert into autor_libro(id_libro,id_autor) values(27,12);
insert into autor_libro(id_libro,id_autor) values(28,13);
insert into autor_libro(id_libro,id_autor) values(30,14);
insert into autor_libro(id_libro,id_autor) values(31,15);
insert into autor_libro(id_libro,id_autor) values(32,15);
insert into autor_libro(id_libro,id_autor) values(33,16);
insert into autor_libro(id_libro,id_autor) values(34,17);
insert into autor_libro(id_libro,id_autor) values(35,18);
insert into autor_libro(id_libro,id_autor) values(35,135);
insert into autor_libro(id_libro,id_autor) values(36,15);
insert into autor_libro(id_libro,id_autor) values(41,19);
insert into autor_libro(id_libro,id_autor) values(42,20);
insert into autor_libro(id_libro,id_autor) values(43,21);
insert into autor_libro(id_libro,id_autor) values(44,22);
insert into autor_libro(id_libro,id_autor) values(45,23);
insert into autor_libro(id_libro,id_autor) values(46,24);
insert into autor_libro(id_libro,id_autor) values(46,111);
insert into autor_libro(id_libro,id_autor) values(47,25);
insert into autor_libro(id_libro,id_autor) values(47,112);
insert into autor_libro(id_libro,id_autor) values(52,26);
insert into autor_libro(id_libro,id_autor) values(53,27);
insert into autor_libro(id_libro,id_autor) values(54,28);
insert into autor_libro(id_libro,id_autor) values(55,29);
insert into autor_libro(id_libro,id_autor) values(56,30);
insert into autor_libro(id_libro,id_autor) values(59,31);
insert into autor_libro(id_libro,id_autor) values(61,32);
insert into autor_libro(id_libro,id_autor) values(62,16);
insert into autor_libro(id_libro,id_autor) values(63,33);
insert into autor_libro(id_libro,id_autor) values(64,33);
insert into autor_libro(id_libro,id_autor) values(65,33);
insert into autor_libro(id_libro,id_autor) values(66,33);
insert into autor_libro(id_libro,id_autor) values(67,33);
insert into autor_libro(id_libro,id_autor) values(68,15);
insert into autor_libro(id_libro,id_autor) values(69,15);
insert into autor_libro(id_libro,id_autor) values(70,15);
insert into autor_libro(id_libro,id_autor) values(71,34);
insert into autor_libro(id_libro,id_autor) values(72,35);
insert into autor_libro(id_libro,id_autor) values(73,15);
insert into autor_libro(id_libro,id_autor) values(74,36);
insert into autor_libro(id_libro,id_autor) values(75,37);
insert into autor_libro(id_libro,id_autor) values(76,37);
insert into autor_libro(id_libro,id_autor) values(77,37);
insert into autor_libro(id_libro,id_autor) values(78,38);
insert into autor_libro(id_libro,id_autor) values(79,39);
insert into autor_libro(id_libro,id_autor) values(80,48);
insert into autor_libro(id_libro,id_autor) values(81,41);
insert into autor_libro(id_libro,id_autor) values(83,42);
insert into autor_libro(id_libro,id_autor) values(84,37);
insert into autor_libro(id_libro,id_autor) values(85,37);
insert into autor_libro(id_libro,id_autor) values(86,36);
insert into autor_libro(id_libro,id_autor) values(87,51);
insert into autor_libro(id_libro,id_autor) values(88,37);
insert into autor_libro(id_libro,id_autor) values(89,15);
insert into autor_libro(id_libro,id_autor) values(90,34);
insert into autor_libro(id_libro,id_autor) values(90,88);
insert into autor_libro(id_libro,id_autor) values(91,34);
insert into autor_libro(id_libro,id_autor) values(91,88);
insert into autor_libro(id_libro,id_autor) values(92,20);
insert into autor_libro(id_libro,id_autor) values(92,15);
insert into autor_libro(id_libro,id_autor) values(93,15);
insert into autor_libro(id_libro,id_autor) values(94,15);
insert into autor_libro(id_libro,id_autor) values(95,15);
insert into autor_libro(id_libro,id_autor) values(96,37);
insert into autor_libro(id_libro,id_autor) values(97,37);
insert into autor_libro(id_libro,id_autor) values(98,37);
insert into autor_libro(id_libro,id_autor) values(99,37);
insert into autor_libro(id_libro,id_autor) values(100,37);
insert into autor_libro(id_libro,id_autor) values(101,37);
insert into autor_libro(id_libro,id_autor) values(102,37);
insert into autor_libro(id_libro,id_autor) values(103,44);
insert into autor_libro(id_libro,id_autor) values(103,113);
insert into autor_libro(id_libro,id_autor) values(103,114);
insert into autor_libro(id_libro,id_autor) values(104,45);
insert into autor_libro(id_libro,id_autor) values(105,45);
insert into autor_libro(id_libro,id_autor) values(106,46);
insert into autor_libro(id_libro,id_autor) values(107,47);
insert into autor_libro(id_libro,id_autor) values(108,48);
insert into autor_libro(id_libro,id_autor) values(108,33);
insert into autor_libro(id_libro,id_autor) values(109,49);
insert into autor_libro(id_libro,id_autor) values(109,33);
insert into autor_libro(id_libro,id_autor) values(110,25);
insert into autor_libro(id_libro,id_autor) values(110,112);
insert into autor_libro(id_libro,id_autor) values(111,112);
insert into autor_libro(id_libro,id_autor) values(111,50);
insert into autor_libro(id_libro,id_autor) values(112,112);
insert into autor_libro(id_libro,id_autor) values(112,48);
insert into autor_libro(id_libro,id_autor) values(113,37);
insert into autor_libro(id_libro,id_autor) values(114,37);
insert into autor_libro(id_libro,id_autor) values(115,25);
insert into autor_libro(id_libro,id_autor) values(116,48);
insert into autor_libro(id_libro,id_autor) values(118,51);
insert into autor_libro(id_libro,id_autor) values(119,52);
insert into autor_libro(id_libro,id_autor) values(119,115);
insert into autor_libro(id_libro,id_autor) values(120,53);
insert into autor_libro(id_libro,id_autor) values(121,54);
insert into autor_libro(id_libro,id_autor) values(122,54);
insert into autor_libro(id_libro,id_autor) values(123,54);
insert into autor_libro(id_libro,id_autor) values(123,116);
insert into autor_libro(id_libro,id_autor) values(124,55);
insert into autor_libro(id_libro,id_autor) values(124,117);
insert into autor_libro(id_libro,id_autor) values(125,55);
insert into autor_libro(id_libro,id_autor) values(125,117);
insert into autor_libro(id_libro,id_autor) values(126,56);
insert into autor_libro(id_libro,id_autor) values(127,55);
insert into autor_libro(id_libro,id_autor) values(128,117);
insert into autor_libro(id_libro,id_autor) values(140,57);
insert into autor_libro(id_libro,id_autor) values(140,118);
insert into autor_libro(id_libro,id_autor) values(141,120);
insert into autor_libro(id_libro,id_autor) values(141,119);
insert into autor_libro(id_libro,id_autor) values(142,57);
insert into autor_libro(id_libro,id_autor) values(142,120);
insert into autor_libro(id_libro,id_autor) values(143,57);
insert into autor_libro(id_libro,id_autor) values(143,120);
insert into autor_libro(id_libro,id_autor) values(144,59);
insert into autor_libro(id_libro,id_autor) values(144,134);
insert into autor_libro(id_libro,id_autor) values(145,60);
insert into autor_libro(id_libro,id_autor) values(146,61);
insert into autor_libro(id_libro,id_autor) values(147,62);
insert into autor_libro(id_libro,id_autor) values(148,63);
insert into autor_libro(id_libro,id_autor) values(149,64);
insert into autor_libro(id_libro,id_autor) values(150,65);
insert into autor_libro(id_libro,id_autor) values(151,66);
insert into autor_libro(id_libro,id_autor) values(152,67);
insert into autor_libro(id_libro,id_autor) values(153,68);
insert into autor_libro(id_libro,id_autor) values(154,69);
insert into autor_libro(id_libro,id_autor) values(154,121);
insert into autor_libro(id_libro,id_autor) values(155,18);
insert into autor_libro(id_libro,id_autor) values(157,70);
insert into autor_libro(id_libro,id_autor) values(158,71);
insert into autor_libro(id_libro,id_autor) values(159,72);
insert into autor_libro(id_libro,id_autor) values(160,73);
insert into autor_libro(id_libro,id_autor) values(161,74);
insert into autor_libro(id_libro,id_autor) values(162,75);
insert into autor_libro(id_libro,id_autor) values(163,76);
insert into autor_libro(id_libro,id_autor) values(164,77);
insert into autor_libro(id_libro,id_autor) values(165,78);
insert into autor_libro(id_libro,id_autor) values(166,79);
insert into autor_libro(id_libro,id_autor) values(168,80);
insert into autor_libro(id_libro,id_autor) values(169,81);
insert into autor_libro(id_libro,id_autor) values(170,82);
insert into autor_libro(id_libro,id_autor) values(171,83);
insert into autor_libro(id_libro,id_autor) values(172,83);
insert into autor_libro(id_libro,id_autor) values(173,83);
insert into autor_libro(id_libro,id_autor) values(174,83);
insert into autor_libro(id_libro,id_autor) values(175,83);
insert into autor_libro(id_libro,id_autor) values(176,83);
insert into autor_libro(id_libro,id_autor) values(177,83);
insert into autor_libro(id_libro,id_autor) values(178,84);
insert into autor_libro(id_libro,id_autor) values(179,48);
insert into autor_libro(id_libro,id_autor) values(180,85);
insert into autor_libro(id_libro,id_autor) values(181,86);
insert into autor_libro(id_libro,id_autor) values(182,87);
insert into autor_libro(id_libro,id_autor) values(184,33);
insert into autor_libro(id_libro,id_autor) values(185,33);
insert into autor_libro(id_libro,id_autor) values(186,33);
insert into autor_libro(id_libro,id_autor) values(187,50);
insert into autor_libro(id_libro,id_autor) values(188,89);
insert into autor_libro(id_libro,id_autor) values(189,33);
insert into autor_libro(id_libro,id_autor) values(190,33);
insert into autor_libro(id_libro,id_autor) values(191,48);
insert into autor_libro(id_libro,id_autor) values(192,33);
insert into autor_libro(id_libro,id_autor) values(193,33);
insert into autor_libro(id_libro,id_autor) values(197,90);
insert into autor_libro(id_libro,id_autor) values(197,122);
insert into autor_libro(id_libro,id_autor) values(198,91);
insert into autor_libro(id_libro,id_autor) values(198,123);
insert into autor_libro(id_libro,id_autor) values(199,92);
insert into autor_libro(id_libro,id_autor) values(200,93);
insert into autor_libro(id_libro,id_autor) values(201,94);
insert into autor_libro(id_libro,id_autor) values(202,95);
insert into autor_libro(id_libro,id_autor) values(202,124);
insert into autor_libro(id_libro,id_autor) values(203,95);
insert into autor_libro(id_libro,id_autor) values(203,124);
insert into autor_libro(id_libro,id_autor) values(204,96);
insert into autor_libro(id_libro,id_autor) values(204,125);
insert into autor_libro(id_libro,id_autor) values(205,97);
insert into autor_libro(id_libro,id_autor) values(206,90);
insert into autor_libro(id_libro,id_autor) values(207,90);
insert into autor_libro(id_libro,id_autor) values(208,90);
insert into autor_libro(id_libro,id_autor) values(209,5);
insert into autor_libro(id_libro,id_autor) values(209,109);
insert into autor_libro(id_libro,id_autor) values(210,98);
insert into autor_libro(id_libro,id_autor) values(211,98);
insert into autor_libro(id_libro,id_autor) values(212,98);
insert into autor_libro(id_libro,id_autor) values(213,99);
insert into autor_libro(id_libro,id_autor) values(213,126);
insert into autor_libro(id_libro,id_autor) values(213,128);
insert into autor_libro(id_libro,id_autor) values(213,127);
insert into autor_libro(id_libro,id_autor) values(214,99);
insert into autor_libro(id_libro,id_autor) values(214,126);
insert into autor_libro(id_libro,id_autor) values(214,128);
insert into autor_libro(id_libro,id_autor) values(214,127);
insert into autor_libro(id_libro,id_autor) values(215,99);
insert into autor_libro(id_libro,id_autor) values(215,126);
insert into autor_libro(id_libro,id_autor) values(215,128);
insert into autor_libro(id_libro,id_autor) values(215,127);
insert into autor_libro(id_libro,id_autor) values(216,100);
insert into autor_libro(id_libro,id_autor) values(217,100);
insert into autor_libro(id_libro,id_autor) values(218,100);
insert into autor_libro(id_libro,id_autor) values(219,101);
insert into autor_libro(id_libro,id_autor) values(219,129);
insert into autor_libro(id_libro,id_autor) values(219,130);
insert into autor_libro(id_libro,id_autor) values(220,101);
insert into autor_libro(id_libro,id_autor) values(220,129);
insert into autor_libro(id_libro,id_autor) values(220,130);
insert into autor_libro(id_libro,id_autor) values(221,101);
insert into autor_libro(id_libro,id_autor) values(221,129);
insert into autor_libro(id_libro,id_autor) values(221,130);
insert into autor_libro(id_libro,id_autor) values(224,100);
insert into autor_libro(id_libro,id_autor) values(228,102);
insert into autor_libro(id_libro,id_autor) values(230,103);
insert into autor_libro(id_libro,id_autor) values(230,131);
insert into autor_libro(id_libro,id_autor) values(232,104);
insert into autor_libro(id_libro,id_autor) values(232,132);
insert into autor_libro(id_libro,id_autor) values(233,5);
insert into autor_libro(id_libro,id_autor) values(233,109);
insert into autor_libro(id_libro,id_autor) values(234,105);
insert into autor_libro(id_libro,id_autor) values(235,106);
insert into autor_libro(id_libro,id_autor) values(236,107);

insert into estatus(estatus) values('solicitando');
insert into estatus(estatus) values('aceptado');
insert into estatus(estatus) values('rechazado');